export default {
  content: [
    "./src/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "background": "#f8f9fb",
        "primary-container": "#4f46e5",
        "secondary-fixed-dim": "#45dfa4",
        "primary-fixed": "#e2dfff",
        "on-tertiary-container": "#d4dbf5",
        "on-secondary-fixed": "#002114",
        "on-secondary-container": "#00714e",
        "slate-text": "#64748B",
        "code-purple": "#A855F7",
        "surface-container-high": "#e7e8ea",
        "surface-container-low": "#f3f4f6",
        "secondary-container": "#64f9bc",
        "inverse-primary": "#c3c0ff",
        "error-container": "#ffdad6",
        "surface-tint": "#4d44e3",
        "tertiary-container": "#586076",
        "on-surface-variant": "#464555",
        "on-secondary": "#ffffff",
        "on-primary": "#ffffff",
        "secondary": "#006c4b",
        "border-subtle": "#E2E8F0",
        "on-error-container": "#93000a",
        "on-surface": "#191c1e",
        "code-cyan": "#22D3EE",
        "primary": "#3525cd",
        "inverse-on-surface": "#f0f1f3",
        "surface-variant": "#e1e2e4",
        "on-error": "#ffffff",
        "inverse-surface": "#2e3132",
        "tertiary-fixed-dim": "#bec6e0",
        "secondary-fixed": "#68fcbf",
        "surface-container-lowest": "#ffffff",
        "on-primary-fixed-variant": "#3323cc",
        "on-secondary-fixed-variant": "#005137",
        "on-primary-fixed": "#0f0069",
        "on-primary-container": "#dad7ff",
        "surface": "#f8f9fb",
        "outline": "#777587",
        "tertiary": "#41485e",
        "on-tertiary-fixed": "#131b2e",
        "surface-bright": "#f8f9fb",
        "tertiary-fixed": "#dae2fd",
        "on-tertiary": "#ffffff",
        "on-background": "#191c1e",
        "on-tertiary-fixed-variant": "#3f465c",
        "error": "#ba1a1a",
        "surface-container": "#edeef0",
        "surface-dim": "#d9dadc",
        "outline-variant": "#c7c4d8",
        "surface-container-highest": "#e1e2e4",
        "surface-card": "#FFFFFF",
        "primary-fixed-dim": "#c3c0ff",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "section-gap": "120px",
        "stack-sm": "8px",
        "component-gap": "24px",
        "gutter": "32px",
        "margin-mobile": "20px",
        "stack-md": "16px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "code-sm": ["JetBrains Mono Variable", "monospace"],
        "headline-md": ["Sora Variable", "sans-serif"],
        "body-lg": ["Inter Variable", "sans-serif"],
        "display-lg": ["Sora Variable", "sans-serif"],
        "body-md": ["Inter Variable", "sans-serif"],
        "display-xl": ["Sora Variable", "sans-serif"],
        "display-lg-mobile": ["Sora Variable", "sans-serif"],
        "label-caps": ["JetBrains Mono Variable", "monospace"],
        "headline-sm": ["Sora Variable", "sans-serif"],
      },
      fontSize: {
        "code-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-lg": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-xl": ["72px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "display-lg-mobile": ["36px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.1em", fontWeight: "600" }],
        "headline-sm": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
